# Generated by Django 5.0.4 on 2025-08-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_sesion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
