# Generated by Django 5.0.4 on 2025-08-29 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='metodo_numerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('documentacion', models.TextField(blank=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos', to='historial.categoria_metodo')),
            ],
        ),
        migrations.CreateModel(
            name='calculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametros_entrada', models.JSONField()),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('procedimiento', models.JSONField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos', to='usuarios.usuario')),
                ('id_metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos', to='historial.metodo_numerico')),
            ],
        ),
        migrations.CreateModel(
            name='parametro_metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parametro', models.CharField(max_length=100)),
                ('tipo_dato', models.CharField(choices=[('int', 'Entero'), ('float', 'Decimal'), ('str', 'Texto'), ('bool', 'Booleano'), ('list', 'Lista'), ('dict', 'Diccionario')], max_length=10)),
                ('id_metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='historial.metodo_numerico')),
            ],
        ),
    ]
