# Generated by Django 5.0.4 on 2025-08-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_metodo',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='metodo_numerico',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parametro_metodo',
            name='nombre_parametro',
            field=models.CharField(max_length=50),
        ),
    ]
