# Generated by Django 5.0.4 on 2025-09-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_alter_categoria_metodo_nombre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='parametro_metodo',
        ),
    ]
